### ISSUE TITLE
Comment faire pour créer des tableaux

### ISSUE THREAD

**Issue by bacus99** [InfotelGLPI/mydashboard#1]
Des lignes, area, piechart?  Je ne vois pas de documentation là-dessus

Est-ce aussi possible d'importer deu plugin MReporting?

Super cool en passant :)

**Comment by tsmr** [comment]
Il faut passer par du développement.
Cordialement

**Comment by bacus99** [comment]
Merci de l'information, mes graphs sont présentement dans MReporting.  Est-ce que le dev sera fait par vous où il sera possible pour nous de faire éventuellement afin d'intégrer complètement MReporting?

**Comment by tsmr** [comment]
Vous avez effectivement 2 options
- Vous développez vous-même l’intégration du plugin mreporting dans le plugin mydashboard en nous fournissant un Pull Request
- Vous passez par nous pour le développement via une prestation
PS : Sous réserve bien sur que l'intégration soit possible
