### ISSUE TITLE
Same Problem: Plugin "MyDashboard" crashes the Plugin Folder

### ISSUE THREAD

**Issue by glpinewbi** [InfotelGLPI/mydashboard#10]
Hey, i downloaded now the Updated Version 1.3.1 from http://plugins.glpi-project.org/#/plugin/mydashboard but it still breaks my whole System. After putting the "mydashboard"- Folder into Plugin-Folder, i get internal Server error and if i came into System the plugin section is blank....

**Comment by amma35** [comment]
Can you test the new release (Version 1.3.1), please?

**Comment by glpinewbi** [comment]
Thank you, it works now :)
