### ISSUE TITLE
Widgets "Numbers of tickets by group (or tech) and status : open blank page

### ISSUE THREAD

**Issue by RodolpheLP** [InfotelGLPI/mydashboard#100]
Hi there,
I have trouble with opening the list of tickets by clicking in two widgets in "mydashboard".
Thanks for your help !

Regards,
RodolpheLP

plugin version : 1.7.7
glpi version : 9.4.6

**to reproduce :**
Add the widget "Number of tickets by technician and by status" or "Number of tickets by group and by status" to your dashboard
![image](https://user-images.githubusercontent.com/52998305/85560323-d49a8700-b62a-11ea-856b-6dd5df263f08.png)

Clic one of the result to open a new tab with the list of tickets results ... unfortunatly is blank... !

**Comment by RodolpheLP** [comment]
Hi,
This is solved by the new version of that plugin : 1.7.8

Thx for that !

**Comment by tsmr** [comment]
Thanks for your reply
