### ISSUE TITLE
Auto refresh?

### ISSUE THREAD

**Issue by enannos** [InfotelGLPI/mydashboard#107]
Hello,

I find your plugin really useful and we have been using it for quite a time now.
Is there a possibility to auto refresh every X minutes all the widgets and generally the Dashboard page?
That would be really great.

Thanks

**Comment by keha35** [comment]
Hello, 

This configuration is in the preferences of the user :
![Capturezzzz](https://user-images.githubusercontent.com/39367117/88393798-91187180-cdbe-11ea-8353-c90129ab1cce.PNG)

**Comment by enannos** [comment]
Thank you, that did the trick. 
Is there a possibility to change the refresh rate for the members of a group or a profile?

That should be very useful to activate for a group of people the autorefresh setting.

Best regards

**Comment by keha35** [comment]
It's not possible for the moment but i had this to our enhancement tag

**Comment by eramos13** [comment]
I have configured 1 minute to update, but the widget still does not refresh. Applies to all widget ?. Also configure activate the automatic update option and not update automatically.

**Comment by tsmr** [comment]
Old ticket i close - open it if needed
