### ISSUE TITLE
Aucun affichage Dashbord "Respect du TTO" & "TTR"

### ISSUE THREAD

**Issue by jpegli** [InfotelGLPI/mydashboard#108]
Bonjour,

- version du plugin : 1.7.8
- version GLPI : 9.4.6

Les 2 dashbords circulaires "Respect du TTO et TTR" n'affichent aucune donnée.
Merci pour votre aide.
Joris

**Comment by keha35** [comment]
Bonjour,

Avez vous configuré des SLA?
Si rien ne s'affiche c'est que le requête sql ne retrouves pas de données correspondant au dashboard.
