### ISSUE TITLE
Sauvegarde de paramétrage des widgets dans les profils par défaut

### ISSUE THREAD

**Issue by jpegli** [InfotelGLPI/mydashboard#109]
Bonjour,

version du plugin : 1.7.8
version GLPI : 9.4.6

Depuis le menu de configuration du dashboard par défaut, j'ai ajouter des widgets pour un profil donné. Comment faire pour sauvegarder le paramétrage des widgets, à savoir le mode récursif toujours à OUI.
Lorsque je me connecte depuis un compte avec ce profil, ce paramétrage n'est pas du tout pris en compte à chaque refresh de la page.
merci à toute l'équipe.
JP

**Comment by keha35** [comment]
Bonjour,

Ce n'est pas possible actuellement.
Il s'agirait d'une évolution a réaliser sur le plugin.
