### ISSUE TITLE
500 internal server error when trying to view tickets per technician

### ISSUE THREAD

**Issue by LuminousWing** [InfotelGLPI/mydashboard#110]
- The version of the plugin.: 1.8.0
- The version of your GLPI. 9.5.1

On the dashboard you have a list of open tickets by technician, when clicking on a technician name I expect to see a list of their tickets, but instead I just get a 500 internal server error.

Is this a problem with the plugin version/compatiblity with 9.5.1 or what causes this?

**Comment by tsmr** [comment]
Hello can you add a screenshot to see which widget is used ?

**Comment by LuminousWing** [comment]
![2020-09-01 12_38_58-GLPI - Dashboard - Home](https://user-images.githubusercontent.com/45965394/91839949-33463780-ec50-11ea-945c-e9cf3fb0c69c.png)
