### ISSUE TITLE
Button refresh widget

### ISSUE THREAD

**Issue by eramos13** [InfotelGLPI/mydashboard#111]
Hi:

I have the following problem with the plugin:
The GLPI-Requests to process - Technical widget is added. The ticket is entered, it is closed, when returning to Mydashboard the ticket does not disappear from the list. Even the widget refresh button is missing. Through google chrome, when inspecting the code, the line of code was added to reload the widget, it reloads and the closed ticket disappears.

The code I add is:

`<button title = "Refresh widget" class = "md-button refresh-icon pull-right" onclick = "refreshWidget ('gs69');">
<i class = "fas fa-sync-alt"> </i>
</button>
`

This button is only displayed when logging in, then if I enter a ticket or another menu and return to the dashboard, it is no longer displayed.

GLPI version: 9.5.2
Plugin version: 1.8.0

**Comment by tsmr** [comment]
Can you try last version ? https://github.com/InfotelGLPI/mydashboard/releases/tag/1.8.1

**Comment by adul3** [comment]
Hi !
I've the same behavior for the refresh button.
The dashboard refreshes no more when i return to it after modifying a ticket or something else.

GLPI version : 9.5.3
mydashboard version : 1.8.1

Regards

**Comment by adul3** [comment]
Hi !

Same symptom with last versions :(

Glpi : 9.5.5
mydashboard : 1.8.1

Regards.

**Comment by tsmr** [comment]
Old ticket. i close
