### ISSUE TITLE
Can't open result in an other tab of the navigator

### ISSUE THREAD

**Issue by RodolpheLP** [InfotelGLPI/mydashboard#112]
Hi,

version of the plugin : 1.8.0
version of glpi : 9.5.3

Steps to follow for test :

1 - Show the widget "Number of tickets open by tech and by status"
2 - Click on a number of ticket in a row
--> A new tab open in the navigator
3 - Close the new tab
4 - Return to the dashboard and click again on the number in the widget
--> No tab will open
5 - Try to reload the dashboard (press F5) and try again
--> No tab will open again

To solve I have to **disconnect from GLPI on reconnect to it**

Thanks for your help,
Regards

---
Bonjour,

version du plugin: 1.8.0
version de glpi: 9.5.3

Étapes à suivre pour le test:

1 - Afficher le widget "Nombre de tickets ouverts par tech et par statut"
2 - Cliquez sur un numéro de ticket d'affilée
-> Un nouvel onglet ouvert dans le navigateur
3 - Fermer le nouvel onglet
4 - Revenez au tableau de bord et cliquez à nouveau sur le numéro dans le widget
-> Aucun onglet ne s'ouvrira
5 - Essayez de recharger le tableau de bord (appuyez sur F5) et réessayez
-> Aucun onglet ne s'ouvrira à nouveau

Pour résoudre, je dois me déconnecter de GLPI lors de la reconnexion

Merci de votre aide,
Cordialement

**Comment by RodolpheLP** [comment]
Important notice : This is the same on a new installation of GLPI 9.5.3 with the plugin in 1.8.0 (I just try it to evacuate the possibility of a problem with my database)

**Comment by tsmr** [comment]
Can you try last version ? https://github.com/InfotelGLPI/mydashboard/releases/tag/1.8.1

**Comment by RodolpheLP** [comment]
Thanks very much this seems to work !
