### ISSUE TITLE
refresh issues : blank widget or wrong results (show an other group of tech in the widgets)

### ISSUE THREAD

**Issue by RodolpheLP** [InfotelGLPI/mydashboard#113]
Hi,

version of the plugin : 1.8.0
version of glpi : 9.5.3

It's very hard to reproduce because the problem doesn't seem to appear regulary.

When users work on a ticket and go back to the dashboard at their startpage of glpi, the widgets may have two appearances :
- empty with the sentence "Aucune donnée disponible"
- not empty but with informations of an other team or another user

That doesn't appear each time but very frequently.
I supposed a problem with navigator's cache but this appears on Firefox (differents versions) Chrome (differents versions) and on any computer.

I don't know where to search for..
Thanks for your help,

Regards

---
Bonjour,

version du plugin: 1.8.0
version de glpi: 9.5.3

C'est très difficile à reproduire car le problème ne semble pas apparaître régulièrement.

Lorsque les utilisateurs travaillent sur un ticket et retournent au tableau de bord à leur page d'accueil de glpi, les widgets peuvent avoir deux apparences:
- vide avec la phrase "Aucune donnée disponible"
- pas vide mais avec les informations d'une autre équipe ou d'un autre utilisateur

Cela n'apparaît pas à chaque fois mais très fréquemment.
J'ai supposé un problème avec le cache du navigateur mais cela apparaît sur Firefox (différentes versions) Chrome (différentes versions) et sur n'importe quel ordinateur.

Je ne sais pas où chercher ..
Merci de votre aide,

Cordialement

**Comment by tsmr** [comment]
Can you try last version ? https://github.com/InfotelGLPI/mydashboard/releases/tag/1.8.1

**Comment by RodolpheLP** [comment]
I'm sorry but I have to say that this doesn't work.
I always have "Pas de données disponible"
![image](https://user-images.githubusercontent.com/52998305/101662525-e7bed900-3a49-11eb-840e-47af4125b759.png)

**Comment by tsmr** [comment]
Did you try to save the dashboard again ?

**Comment by RodolpheLP** [comment]
I'm on it.
I am trying to reset widget configuration on each profil and test it again.

**Comment by RodolpheLP** [comment]
After many tests this seems to work with :
- plugin version 1.8.1
- after uninstalling previous version and reset all users parameters

**Comment by RodolpheLP** [comment]
After many tests this seems to work with :
- plugin version 1.8.1
- after uninstalling previous version and reset all users parameters
