### ISSUE TITLE
Widget vue groupe

### ISSUE THREAD

**Issue by AtomHub89** [InfotelGLPI/mydashboard#114]
Bonjour,

Version du plugin : 1.7.8
GLPI 9.4.6

Est il possible d'ajouter une colonne Assigné A, dans la vue groupe, pour obtenir le nom du technicien affecté à un ticket, sans changer de version GLPI.

Merci par avance,

**Comment by tsmr** [comment]
Old ticket i close - open it if needed - see sales team
