### ISSUE TITLE
Probleme de lien vers les tickets dans le widget nombre de tickets ouverts par groupe et par statut

### ISSUE THREAD

**Issue by noordo59** [InfotelGLPI/mydashboard#115]
Bonjour,

je suis en GLPI 9.4.5 et plugin my dashboard 1.7.7.

J'affiche le widget "nombre de tickets ouverts par groupe et par statut" pour le profil super admin.
Le nombre de ticket en cours (Attribué), en cours (Planifié), En attente et Résolu s'affiche bien pour chaque groupe mais le clic sur un chiffre du tableau (par exemple le nombre de tickets en cours (Attribué) pour le groupe A) ne fonctionne pas.
Un nouvel onglet du navigateur s'ouvre bien mais aucun lien n'est associé. Capture d'écran en PJ.

Pouvez vous m'indiquer le fichier ou la portion de code à modifier?

D'avance merci beaucoup
![2021-02-12 15_00_16-GLPI - Dashboard](https://user-images.githubusercontent.com/78965954/107777557-47d04500-6d43-11eb-8fa7-6e753a1d3a58.png)
![2021-02-12 15_00_33-](https://user-images.githubusercontent.com/78965954/107777564-4b63cc00-6d43-11eb-8a1c-7912b9d16988.png)

**Comment by tsmr** [comment]
Old ticket i close - open it if needed
