### ISSUE TITLE
PHP Error when accessing mydashboard with SUper-Admin profile

### ISSUE THREAD

**Issue by ZeikoFr** [InfotelGLPI/mydashboard#116]
Plugin version : 1.8.1
GLPI 9.5.3 
- The steps to reproduce your issue.
Use Super-Admin or user profile
Go to : https://mydomain/plugins/mydashboard/front/menu.php

this is what the debug mode answer
PHP Notice (8): Undefined variable: gslist in /data/webs/web-3727/plugins/mydashboard/inc/menu.class.php at line 802
PHP Notice (8): Undefined variable: gslist in /data/webs/web-3727/plugins/mydashboard/inc/menu.class.php at line 807

I can only use the admin account (that as the same right a super admin for internal reason) to access this dashboard

**Comment by tsmr** [comment]
Old ticket i close - open it if needed
