### ISSUE TITLE
GLPI 9.5.4 - widgets disappear except "global view" and "dashboard"

### ISSUE THREAD

**Issue by RodolpheLP** [InfotelGLPI/mydashboard#117]
Hi everyone,

When I migrate GLPI from 9.5.3 to 9.5.4 some widgets disapeared.

This is what I have in widget selection from 9.5.3 version of GLPI :
![image](https://user-images.githubusercontent.com/52998305/110324303-10894700-8016-11eb-92e4-747ef5e5a4c1.png)

This is what I have in widget selection in 9.5.4 version of GLPI :
![image](https://user-images.githubusercontent.com/52998305/110324384-2bf45200-8016-11eb-81fd-7918cbf03390.png)

All of this appear with super-admin profil.

Thanks for your help,
Regards

**Comment by RodolpheLP** [comment]
Hello again,

I also tried to remove the mydashboard plugin and reinstall it but the problem persists.

Thanks for your help,

**Comment by adul3** [comment]
Hi,
Same problem for me... Updated GLPI 9.5.3 to 9.5.4, with mydashboard 1.8.1 installed.
Some widgets have disapeared.
All user profiles are impacted.
In edit mode, unable to add the lists of tickets for user or group.
In the users profiles configuration, in the "mydashboard" tab, some widgets are absent in the autorization list.
Uninstalling then installing the plugin does not correct the issue.

**Comment by Sanlokii** [comment]
Hi,
Same case here, update from 9.5.3 to 9.5.4 with version 1.8.1 mydashboards.
Thanks.

**Comment by tsmr** [comment]
Can you try this ?

https://github.com/InfotelGLPI/mydashboard/commit/212f69571ddc45057cd8cbd99068e5d81d9a4658#diff-d37ff6db2c6617111fed10cfcd07bc4783f1f81fd44ce0d80b01a42a2a597d4d

**Comment by RodolpheLP** [comment]
> Can you try this ?
> 
> [212f695#diff-d37ff6db2c6617111fed10cfcd07bc4783f1f81fd44ce0d80b01a42a2a597d4d](https://github.com/InfotelGLPI/mydashboard/commit/212f69571ddc45057cd8cbd99068e5d81d9a4658#diff-d37ff6db2c6617111fed10cfcd07bc4783f1f81fd44ce0d80b01a42a2a597d4d)

Hi,
Thanks for your help tsmr but this doesn't seem to solve the problem :
![image](https://user-images.githubusercontent.com/52998305/110628827-c8982a80-81a3-11eb-8434-46476d9a5846.png)

**Comment by RodolpheLP** [comment]
Hello Tsmr,
Why did you close this thread ? For me it still doesn't work like I say it in my message upthere.

Did you find the solution to solve the problem ?

Regards,

**Comment by tsmr** [comment]
Yes with this commit : https://github.com/InfotelGLPI/mydashboard/commit/337145db6c38ff7f9bdf36a3d699ceb208ce3db8

**Comment by RodolpheLP** [comment]
> Yes with this commit : [337145d](https://github.com/InfotelGLPI/mydashboard/commit/337145db6c38ff7f9bdf36a3d699ceb208ce3db8)

I'm sorry but I tried this and it doesn't seem to work for me.
Did I have to delete cache or restart something elsewhere to make it works ?

Thanks for your answer,
Regards,

**Comment by RodolpheLP** [comment]
My apologies...
This works for me.
I made a mistake on which files I had to edit : I edited files in \inc\ directory instead of \reports\.
Thanks a lot for your help tsmr !
