### ISSUE TITLE
GLPI Crash on installing Plugin Mydashboard 1.2.1 with GLPI 0.90.1

### ISSUE THREAD

**Issue by camala19** [InfotelGLPI/mydashboard#12]
- MyDashboard 1.2.1
- version GLPI 0.90.1
- Installation de MyDashboard de manière classique.
Problème avec la base MYSQL qui ne veut pas redémarrer

Alain Cambou

**Comment by amma35** [comment]
Pouvez-vous me dire si vous avez des erreurs dans les fichiers de log, c'est à dire dans files/_log/php-errors.log et sql-errors.log concernant le plugin ?

**Comment by camala19** [comment]
Bonjour,
Le service MySQL a planté lors de l'installation du plugin. Impossible de
le relancer.
Pour résoudre le problème, il a fallu "Killer" manuellement tous les
processus MySQL restant actifs et relancer le service.
Ensuite on a remis, au niveau de la base SQL, le plugin au statut normal et
tout fonctionne de nouveau désormais.

Merci pour votre retour en tout cas.



Cordialement

*Alain CAMBOU*

«Tout le monde est un génie. Mais si vous jugez un poisson sur sa capacité
à grimper à un arbre, il passera sa vie à croire qu’il est stupide. » –
Albert Einstein -

2017-01-19 16:44 GMT+01:00 Amandine Manceau <notifications@github.com>:
