### ISSUE TITLE
deleted ticket

### ISSUE THREAD

**Issue by grenona** [InfotelGLPI/mydashboard#120]
- The version of the plugin:1.8.2
- The version of your GLPI.9.5.6
-
step one If i filter the ticket to see ticket with task. in the dashboard
step two: i delete ex: ticket ID 25
step 3: My dashboard still show up the ticket 25 in the list, i click on it, on the bottom of the ticket, i have option: 
Restore or permenent delete
step 4 i delete permennent the ticket, now it dissapear from my dashboard list

**Comment by tsmr** [comment]
Hello

Which widget is concerned ?

**Comment by grenona** [comment]
***@***.***

**Comment by tsmr** [comment]
Sorry but i haven't informations in your mail. Please use github interface

**Comment by grenona** [comment]
HI The widget is Ticket tasks to do - Group View

**Comment by tsmr** [comment]
It's a bug of GLPI (I use a function of GLPI)

**Comment by grenona** [comment]
Thanks did the bug is reported
