### ISSUE TITLE
Widget Annuaire - Non mis à jour LDAP

### ISSUE THREAD

**Issue by Hide65** [InfotelGLPI/mydashboard#128]
Dear GLPi user.

For bug reports, you can open an issue here, provide us : 
- The version of the plugin. 2.0.4
- The version of your GLPI. 10
- The steps to reproduce your issue.

J'ai sur un serveur test sous ubuntu une version de GLPI 10 et le plugin MYDASHBOARD 2.0.4, je me sers principalement de l'annuaire pour les utilisateurs.

Lors de l'installation, il récupère bien tous les utilisateurs.

Mais quand :
- j'importe des users depuis la liaison AD, ils remontent bien dans glpi > utilisateurs, il ne remonte pas dans le plugin
- je crée un users manuel dans GLPI, il remonte dans le plugin.

**Comment by tsmr** [comment]
Il n'y a pas de raison. Il faut qu'ils aient un profil dans l'entité active et au moins un champ de téléphone rempli)

**Comment by Hide65** [comment]
Effectivement il n'y avait rien dans le profil.
Désolé.
