### ISSUE TITLE
Problème de fonctionnement après maj vers GLPI 10

### ISSUE THREAD

**Issue by sblanchouin** [InfotelGLPI/mydashboard#129]
Bonjour,

Tout d'abord, merci pour le travail que vous faites 👍 

J'ai mis à jour mon GLPI de la version 9.5.7 vers la version 10.0.2. Suite à la migration, certains plugins n'étaient pas à jour. J'ai donc passé le plugin de la version 1.8.2 vers la version 2.0.4

Depuis cette mise à jour, le plugin fonctionne sauf pour le widget "Stock de ticket par mois"

Les données semblent bien présentes en BDD pourtant...

![2022-08-31 15_29_45-Dashboard - GLPI - Travail – Microsoft​ Edge](https://user-images.githubusercontent.com/112562085/187692129-7953c945-b0ba-4a7c-8350-cc35cba65035.png)
![2022-08-31 15_26_56-GLPI_glpi_glpi_plugin_mydashboard_stocktickets_ - HeidiSQL 11 3 0 6295](https://user-images.githubusercontent.com/112562085/187692135-35192295-9798-43c4-9c03-c4cdb5ab045b.png)

Que se passe-t-il ? Comment résoudre ce problème ?

Merci pour votre aide :)

**Comment by tsmr** [comment]
Ca doit être résolu en dernière version
