### ISSUE TITLE
GLPI 9.5.5 / Mydashboard 1.8.3 : Configuration profil

### ISSUE THREAD

**Issue by EC2311** [InfotelGLPI/mydashboard#130]
Bonjour

En super-admin : tout accés : ok
**pas de configuration personnalisée.**

- Un utilisateur connecté en super-admin obtient une page : pas de widget, alors que de mon cote en superadmin j'ai bien une page avec les tableaux...

- Comment retirer l'accés à cette vue par defaut ? : des personnes superadmins ne souhaitent pas voir cette vue lorsqu'ils se connectent sur GLPI

Merci

**Comment by tsmr** [comment]
Il faut configurer  un dashboard par défaut pour le profil
![image](https://user-images.githubusercontent.com/13178158/191707639-0bd38b7a-7555-477a-91e8-ceb6deb5f1c1.png)

Ou modifier dans les préférences utilisateur et/ou dans la configuration : Remplacer l'interface centrale

**Comment by EC2311** [comment]
Bonjour
Merci pour la reponse, en effet pour profil et dashboard par defaut : ok

On peut cloturer
Merci
