### ISSUE TITLE
BUG Indicateurs globaux semaine - mydashboard 1.8.3

### ISSUE THREAD

**Issue by EC2311** [InfotelGLPI/mydashboard#132]
Bonjour

Dans le widget "indicateurs globaux semaines" plusieurs petits bugs : 
- la selection semaine /groupe / annee est impossible : l'action envoyer est sans effet
- l'appui 'tickets clos' envoie sur "ticket en cours"

possibilité d'ajouter l'indicateur "tickets resolus" ?

Merci

**Comment by EC2311** [comment]
petit up ?
Merci

**Comment by EC2311** [comment]
Si cela peut aider pour la resolution : je n'ai pas de gsid renseigné pour le widget correspondant à celui de la semaine...
![image](https://user-images.githubusercontent.com/42341169/195873389-530fb87e-8b9a-4b0c-b30c-658584208692.png)

**Comment by EC2311** [comment]
Bonjour

Merci beaucoup pour les modifs. 👍 

petites confirmations : 
- pour quelle version avez vous realisé les corrections ? en effet j'ai un petit decalage avec les numéros de lignes (je suis en 1.8.3)
- dans inc/widget.class, lorsque je mets en commentaire le global $CFG_GLPI, celui-ci genere des erreurs en ligne 416, lors de l'utilisation de $cfg_glpi
![image](https://user-images.githubusercontent.com/42341169/196113144-da0c7608-2d57-44c6-97bc-7775fe977433.png)

Merci

**Comment by tsmr** [comment]
Bonjour
- Je code pour la version compatible v10 de GLPI
- pour la fonction cron, il faut lancer via cron système, front/insert_stock_ticketindicators.php

**Comment by EC2311** [comment]
👍 
Merci bien
