### ISSUE TITLE
EVO : Possibilité de travailler par numero semaine

### ISSUE THREAD

**Issue by EC2311** [InfotelGLPI/mydashboard#134]
Bonjour

certains widgets affichent les données par mois : ok

y aurait-il possibilité (via selection) de pouvoir saisir numéro de semaine et donc de voir le nombre correspondant à la semaine selectionnée ?

Merci

**Comment by tsmr** [comment]
Bonjour, nécessite un développement assez conséquent. Se rapprocher de notre équipe commerciale.
