### ISSUE TITLE
SQL Error "1064": You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CONSTRAINT `glpi_plugin_mydashboard_userwidgets_ibfk_1`' at line 1 in query "ALTER TABLE `glpi_plugin_mydashboard_userwidgets` DROP CONSTRAINT `glpi_plugin_mydashboard_userwidgets_ibfk_1`" Task Completed. (0 seconds)

### ISSUE THREAD

**Issue by NazarovRoman** [InfotelGLPI/mydashboard#136]
Dear GLPi user.

For bug reports, you can open an issue here, provide us : 
- The version of the plugin.
- 2.0.8
- The version of your GLPI.
- 10.0.3
- The steps to reproduce your issue.
Error when updating plugin

SQL Error "1064": You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CONSTRAINT `glpi_plugin_mydashboard_userwidgets_ibfk_1`' at line 1 in query "ALTER TABLE `glpi_plugin_mydashboard_userwidgets` DROP CONSTRAINT `glpi_plugin_mydashboard_userwidgets_ibfk_1`"
Task Completed. (0 seconds)

![2022-10-19_135051](https://user-images.githubusercontent.com/40058572/196630574-fd757838-acb9-4556-9841-019b5e078f22.png)

Delete this text to submit your issue.

The Plugin team.

**Comment by tsmr** [comment]
with mysql

ALTER TABLE `glpi_plugin_mydashboard_userwidgets` DROP CONSTRAINT `glpi_plugin_mydashboard_userwidgets_ibfk_1`;
