### ISSUE TITLE
impossible to add widget

### ISSUE THREAD

**Issue by satyan01** [InfotelGLPI/mydashboard#14]
Hello I would like to user your plugin but I can't add anything, I can just click on the line and nothing happen

![image](https://cloud.githubusercontent.com/assets/15144026/24705069/8a2636f2-1a0a-11e7-95aa-fb9175da6b30.png)

in debug mode I have that
PHP Notice: Undefined property: DB::$execution_time in C:\inetpub\wwwroot\glpi\inc\dbmysql.class.php at line 193

**Comment by amma35** [comment]
The version of the plugin?
The version of your GLPI?

**Comment by satyan01** [comment]
Hello

plugin 1.3.2
glpi 9.1.1

**Comment by amma35** [comment]
Have you errors in /glpi/files/_log/sql-errors.log?

**Comment by amma35** [comment]
There is no DB :: $ execution_time variable in the GLPI version 9.1.1.

Are you on the GLPI version?

**Comment by satyan01** [comment]
maybe 9.2

**Comment by amma35** [comment]
The plugin is not compatible with version GLPI 9.2

**Comment by satyan01** [comment]
arf too bad
