### ISSUE TITLE
A bug appears randomly when widening a widget

### ISSUE THREAD

**Issue by sylvainclerc** [InfotelGLPI/mydashboard#16]
Hello,

Glpi version : 9.1.6
Plugin myDashboard : 1.3.2
Browsers : Internet Explorer, Firefox, Vivaldi, Chrome, Opera

When widening a widget, sometimes, the order of the widgets changes.

In the enlarge view of a widget, we already have the feature which can move widgets (cf image in attachment) : this feature seems to be useless in the enlarge view ?

If this feature is disabled, it's possible that this bug disappears.

Thanks in advance.
![screenshot069](https://user-images.githubusercontent.com/25950425/30963761-f984b28e-a44e-11e7-9cd5-ac100e42ff50.jpg)

**Comment by amma35** [comment]
in the enlarged view of a widget, do you perform actions?
I can not reproduce your bug.

**Comment by sylvainclerc** [comment]
Yes,

The problem can be reproduce in the enlarge view in my case.

**Comment by tsmr** [comment]
Try with 9.2.X version
