### ISSUE TITLE
Metrics : ERROR 500

### ISSUE THREAD

**Issue by JulienG78** [InfotelGLPI/mydashboard#17]
Bonjour,

J'ai mis à jour mon GLPI en 9.2 et le plugin en 1.4.0 mais je rencontre un soucis majeur maintenant.
J'utilise l'affichage metrics comme dashboard de supervision dans les bureaux pour voir en temps réel les tickets.
Maintenant quand je clic dessus j'ai une erreur 500, impossible d'afficher la page metrics/index.php, indexw et indexb, même erreur.

Un soucis dans la mise à jour ou un truc à corriger de mon coté ?
Merci par avance,

**Comment by tsmr** [comment]
Désolé , mais vous n’êtes pas sur bon site projet. Le plugin Dashbaard est géré la : https://github.com/stdonato/glpi-dashboard
