### ISSUE TITLE
Nouveau widgets tickets

### ISSUE THREAD

**Issue by JulienG78** [InfotelGLPI/mydashboard#18]
Bonjour,

Je voudrais savoir s'il existe un moyen facil de créer de nouveaux widgets pour les tickets ?

Par exemple, je trouve qu'il manque un widget extrêmement important pour voir les tickets en cours en vue groupe. En effet en vue groupe le seul widget ticket disponible est pour les tickets à traiter, mais impossible de voir les tickets en cours, afin de voir les tickets de son équipe.

c'est bien dans le fichier ticket.class.php ?

Merci par avance,

**Comment by amma35** [comment]
Bonjour,

Les principales modifications sont à effectuer dans le fichier ticket.class.php pour les widgets des tickets.
Vous pouvez proposer un Pull requests pour avoir ces modifications lors des futures versions.
