### ISSUE TITLE
No content 

### ISSUE THREAD

**Issue by satyan01** [InfotelGLPI/mydashboard#2]
![image](https://cloud.githubusercontent.com/assets/15144026/17176132/319d2522-5403-11e6-92d7-bbe52d36773d.png)

No php error, no mysql error

![Uploading image.png…]()

**Comment by tsmr** [comment]
Have you defined default dashboard into http://.../plugins/mydashboard/front/config.form.php ?

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/17177057/7d67c04e-5407-11e6-9b4c-6391a0137434.png)

yes but no content

**Comment by satyan01** [comment]
Sorry bad selection of widgets. it works

**Comment by tsmr** [comment]
Which widget ? for your bad selection ?

**Comment by satyan01** [comment]
I did not see anything when i was with full rights on the plugin, I had change to custom and select which widgets I wanted

**Comment by tsmr** [comment]
ok
