### ISSUE TITLE
Problème affichage planning

### ISSUE THREAD

**Issue by prohand** [InfotelGLPI/mydashboard#22]
Bonjour,

For bug reports, you can open an issue here, provide us : 
Glpi version : 9.2.1
Plugin myDashboard : 1.4.0
Browsers : Internet Explorer, Firefox

J'ai un problème et une question concernant le vue du planning sur le dashboard.

Problème : 

Le titre du message ne s'affiche pas (En gros très peu d'information et on ne peut même pas cliquer dessus) (Voir copie d'écran) : 
![2018-01-12 08_58_28-glpi - dashboard](https://user-images.githubusercontent.com/20227162/34864947-e2a24344-f776-11e7-9658-61f0868b1e6b.png)

Question : 

Est-il possible d'afficher toute la semaine ou le mois complet sur le planning au lieu du jour même ?

Merci,

**Comment by tsmr** [comment]
Corrected in next version (1.5.1)
