### ISSUE TITLE
Error extract .xls and setting "period index page"

### ISSUE THREAD

**Issue by juveboss** [InfotelGLPI/mydashboard#23]
Hello the team, 

1) I have a problem when I try to extract in .**xls in Graph / Category** ... don't work !

2) And a problem when I display the **setting - Period in the index page:**
    If I choose a year, the page loads and the parameter is not taken into account

![image](https://user-images.githubusercontent.com/31047406/35285863-b4503c1c-005e-11e8-83d6-24cdf69a011e.png)

Version plugin : 0.9.0
Version glpi : 9.1.6

**Comment by amma35** [comment]
This is not the good plugin.
https://github.com/stdonato/glpi-dashboard
