### ISSUE TITLE
Dashboard toujours en mode edition

### ISSUE THREAD

**Issue by prohand** [InfotelGLPI/mydashboard#25]
Bonjour,

Je ne sais pas si cela est normal mais lorsque l'on est pas en mode édition on peut toujours déplacer les fenêtres. Ce qui est assez embêtant car quand on doit utiliser une barre de scrole, on peut déplacer la fenêtre.

Version plugin : 1.5.0
Version GLPI : 9.2.2

Merci d'avance,

**Comment by amma35** [comment]
Bonjour,

C'est le fonctionnement normal du plugin.
Attention, cette version est une version de développement.
