### ISSUE TITLE
Predefined views accessible to all

### ISSUE THREAD

**Issue by typtop21** [InfotelGLPI/mydashboard#27]
Hi
- The version of the plugin : 1.5.0
- The version of your GLPI : 9.2.3

How to hide the predefined views for a lambda user ?

![capture d ecran 2018-06-18 a 15 38 20](https://user-images.githubusercontent.com/20817253/41539307-bddd6fb2-730d-11e8-990e-2127c0138d2a.png)

**Comment by tsmr** [comment]
The predefined views are not available for simplified interface.

You are into full interface here.

**Comment by typtop21** [comment]
OK it's ok.
But, the user can not rearrange the blocks that are allowed to see : it's a pity for him ;-)

**Comment by tsmr** [comment]
Not the post-only profile
