### ISSUE TITLE
Group not retained in the assigned ticket view

### ISSUE THREAD

**Issue by typtop21** [InfotelGLPI/mydashboard#28]
Hello

The plugin version: 1.5.0
The version of your GLPI: 9.2.3

The view "Number of tickets affected by technicians per month" does not retain the group

![capture d ecran 2018-06-18 a 15 42 10](https://user-images.githubusercontent.com/20817253/41539991-6364a4b8-730f-11e8-95f4-d89974a30b32.png)

The supervisor is not part of the technicians group but he must be able to supervise their work.
If he is one of them, he stands out as a fourth technician without an assigned ticket.

**Comment by tsmr** [comment]
I made corrections into 1.5.1 version.

**Comment by typtop21** [comment]
great thanks for us ;-)
