### ISSUE TITLE
Improve refresh time with tabs ?

### ISSUE THREAD

**Issue by typtop21** [InfotelGLPI/mydashboard#29]
Hello
The version of the plugin : 1.5.0
The version of your GLPI : 9.2.3

Could there be a system of tabs which would allow to have a better refresh time when the view includes many metrics ?

**Comment by tsmr** [comment]
Not so easy..

**Comment by typtop21** [comment]
is that I think too ;-)
good job nevertheless

**Comment by keha35** [comment]
Hi,

We have just released a new version(1.6.4) which gratly improve the plugin performance.

I'm closing the issue, if this release didn't answer your problem feel free to reopen it.
