### ISSUE TITLE
Compose a view with n times the same metric to give all its information at once ?

### ISSUE THREAD

**Issue by typtop21** [InfotelGLPI/mydashboard#30]
Hello
The version of the plugin : 1.5.0
The version of your GLPI : 9.2.3
Could not there be the possibility to deposit a metric 3 times so that the view can show at once: the total of tickets, the number of incidents and finally the number of requests per technician ?

**Comment by typtop21** [comment]
I had not thought about this type of representation but I take : it is the representation that the technician when he will have connected ?

What I want to show is over 1 year, the total number of tickets processed for a technician with incident / demand difference; and icing on the cake, for all the technicians during the same period, the representation in stick request / incident

**Comment by tsmr** [comment]
You can use graph "Number of tickets affected by technicians by month" and use search engine for select the year & the type of tickets

**Comment by typtop21** [comment]
Actually it is this view that I put, nevertheless, by default, it offers the display on the year -which is perfect- but I wish to be able to display also for the type incident and type request without having to go to select these properties

**Comment by tsmr** [comment]
Old ticket. I close
