### ISSUE TITLE
Undefined index: edit_mode

### ISSUE THREAD

**Issue by gmourani** [InfotelGLPI/mydashboard#32]
Hello,

I'm not able to edit the dashboard to select a pre-configured template or something else.

Steps:
I've installed the new version of mydashboard under the plugin directory of GLPI.
I've imported a backup of my previous GLPI DB (mysql -u root glpi < glpi.sql -pxxx).
I've activated the mydshboard plugin in GLPI.

mydashboard 1.5.0
GLPI 9.2.3

  *** PHP Notice(8): Undefined index: edit_mode
  Backtrace :
  plugins/mydashboard/inc/preference.class.php:168   
  plugins/mydashboard/inc/preference.class.php:161   PluginMydashboardPreference::checkPreferenceValue()
  plugins/mydashboard/inc/menu.class.php:232         PluginMydashboardPreference::checkIfPreferenceExists()
  plugins/mydashboard/inc/menu.class.php:174         PluginMydashboardMenu->showDashboard()
  plugins/mydashboard/inc/menu.class.php:856         PluginMydashboardMenu->showMenu()
  plugins/mydashboard/front/menu.php:94              PluginMydashboardMenu->loadDashboard()

Regards,

**Comment by amma35** [comment]
Hi,
Do you have SQL errors when installing the plugin?

**Comment by keha35** [comment]
Hello,

Can you try with the new release 1.5.1 if you still have this problem ?

**Comment by amma35** [comment]
I'm closing for now, feel free to reopen if issue persists.
