### ISSUE TITLE
Amélioration du Planning / Improved schedule

### ISSUE THREAD

**Issue by aze789** [InfotelGLPI/mydashboard#34]
Bonjour,

J'aimerais savoir si il serait possible d'améliorer le plugin afin que celui-ci puisse faire apparaître le planning des autres utilisateur dans le widget planning du Dashboard ?

-------------------------------------------------------------------------------------------------------------------
Hi,

I would like to know if it's possible to update the plugin so that this one can make appear the schedule of the other users in the schedule's widget of Dashboard ?

**Comment by amma35** [comment]
For plugin evolutions, it is necessary to go through a specific development that we realize for our customers.
