### ISSUE TITLE
Support GLPI 9.3 ?

### ISSUE THREAD

**Issue by almeidajeff** [InfotelGLPI/mydashboard#42]
Hello,
I know that maybe here is not the best channel to ask, but I wonder if this plugin already supports the latest version 9.3 of GLPI ?

**Comment by xanvalo** [comment]
Hi,
I also want to ask when to support GLPI 9.3 ???Thanks a lot

**Comment by keha35** [comment]
Hello,

The new release for GLPI 9.3 is now availaible.

**Comment by almeidajeff** [comment]
Great ! 

Thank you
