### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by xanvalo** [InfotelGLPI/mydashboard#43]
**[Initial]**

- GLPI 9.3

- Latest version of plugin from https://github.com/InfotelGLPI/mydashboard.git

**[Steps to reproduce]**
- copy files to plugins folder
- chmod 777 -R folder-name-of -plugin
- click button install from plugin intreface in GLPI

**[Screenshot]**
![image](https://user-images.githubusercontent.com/11530036/43321522-15c4504c-91a4-11e8-9593-44d8a98be57c.png)

![image](https://user-images.githubusercontent.com/11530036/43321747-bec969d4-91a4-11e8-853b-d985323618f8.png)

**Comment by xanvalo** [comment]
This is a fresh install

**Comment by tsmr** [comment]
Into mydashboard\install\sql\empty-1.6.0.sql

Can you try to delete line : 

`FOREIGN KEY (`users_id`) REFERENCES glpi_users (id)`

into

```
CREATE TABLE `glpi_plugin_mydashboard_userwidgets` (
  `id`         INT(11) NOT NULL AUTO_INCREMENT, -- id
  `users_id`   INT(11) NOT NULL
  COMMENT 'RELATION to glpi_users(id)',
  `widgets_id` INT(11) NOT NULL, -- id du widget
  `place`      INT(11) NOT NULL, -- placement du widget
  PRIMARY KEY (`id`),
  FOREIGN KEY (`users_id`) REFERENCES glpi_users (id)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8
  COLLATE = utf8_unicode_ci;
```

And try to install ?

**Comment by tsmr** [comment]
In fact your glpi_users table is not in InnoDB & the glpi_plugin_mydashboard_userwidgets is in InnoDB

**Comment by xanvalo** [comment]
I will try to switch to innodb and test again

**Comment by xanvalo** [comment]
my database engine was not innodb
When i switch to innodb engine problem was solved

**Comment by if13** [comment]
Hi, dear friends!
Got the same error during the installation of the plugin. 
"1.0.4 multiple alter in glpi_plugin_mydashboard_userwidgets - Ошибка во время запроса базы данных: ALTER TABLE `glpi_plugin_mydashboard_userwidgets` ADD `interface` TINYINT(1) NOT NULL DEFAULT '0' - Ошибка - Table 'glpi.glpi_plugin_mydashboard_userwidgets' doesn't exist "

As I understand it, the engine is correct. 
![image](https://user-images.githubusercontent.com/32564563/54808535-84977c80-4c91-11e9-90ff-854dfead2364.png)

What else could be the problem?

**Comment by keha35** [comment]
Hi,

Can you check the engin of each glpi_ tables ?
You can use the script innodb_migration available in /glpi/scripts/ to migrate all tables.

**Comment by if13** [comment]
In 9.4 migration to innodb can be used via /bin/console. Not via script. And i migrate it. Can u tell me about cheking engine each glpi tables? How  i can do it?

**Comment by keha35** [comment]
Bonjour,

Vous pouvez voir l'ensemble des tables avec leur engine via cette commande mysql :
SELECT TABLE_NAME, ENGINE FROM information_schema.TABLES where TABLE_SCHEMA = 'databaseName';
