### ISSUE TITLE
Only works for Super-Admin GLPI 9.3

### ISSUE THREAD

**Issue by jogood** [InfotelGLPI/mydashboard#46]
- The version of the plugin. 
9.3
- The version of your GLPI. 
9.3
- The steps to reproduce your issue.
Give rights to a profile to have dashboard and change widgets.
Login with a user that as this profile
Go to dashboard and try to add any widget.
Clicking on add widget does nothing.

The same can be reproduced from the default dashboard page from Super-Admin on a different profile.

**Comment by amma35** [comment]
Warning: there are two modes in the "Full" and "Custom" profile:
![mydashboard](https://user-images.githubusercontent.com/15138371/45030758-31d7d980-b04d-11e8-9827-ca2192901904.png)
