### ISSUE TITLE
Edit mod global bug in 1.6.1

### ISSUE THREAD

**Issue by jogood** [InfotelGLPI/mydashboard#47]
- The version of the plugin. 
1.6.1 
- The version of your GLPI. 
9.3
- The steps to reproduce your issue.
Go to MyDashboard, click on edit global. The following appear and the plugin won't work anymore.
![image](https://user-images.githubusercontent.com/17586546/45104452-22fe2f00-b100-11e8-8047-ac279c204ad1.png)

Thank you.

**Comment by amma35** [comment]
We have modified, this version cannot be used for GLPI 9.3.0
