### ISSUE TITLE
Global edition mode for mydashboard plugins

### ISSUE THREAD

**Issue by starXsmarcos** [InfotelGLPI/mydashboard#48]
Glpi v9.3
mydashboard v1.6.1

Hello guys,

There is an issue in the plugin when we click on "Configurate and save default dashboard", after clicking on "Tools", "Dashboard".

Here's the caught error : 

**Mode édition (Global)  : 
Fatal error: Uncaught Error: Call to undefined method Profile::getUnderActiveProfileRestrictCriteria() in /var/www/html/glpi2/plugins/mydashboard/inc/menu.class.php:282 Stack trace: #0 /var/www/html/glpi2/plugins/mydashboard/inc/menu.class.php(388): PluginMydashboardMenu::dropdownProfiles(Array) #1 /var/www/html/glpi2/plugins/mydashboard/inc/menu.class.php(324): PluginMydashboardMenu->displayEditMode('2', '4', 0, 1316708124) #2 /var/www/html/glpi2/plugins/mydashboard/inc/menu.class.php(243): PluginMydashboardMenu->showDashboard('4', 0, 1316708124) #3 /var/www/html/glpi2/plugins/mydashboard/inc/menu.class.php(1073): PluginMydashboardMenu->showMenu('2', '4', 0, 1316708124) #4 /var/www/html/glpi2/plugins/mydashboard/front/menu.php(103): PluginMydashboardMenu->loadDashboard('4', 0) #5 {main} thrown in /var/www/html/glpi2/plugins/mydashboard/inc/menu.class.php on line 282**

After that, it's impossible to get out of this

I found the solution by editing table "glpi_plugin_mydashboard_preferences".
Set column "edit_mode" from 2 to 1

Thanks guys

**Comment by amma35** [comment]
duplicate #47 
GLPI 9.3.1 : Version 1.6.1 disponible / available
Do not use for GLPI 9.3.0
