### ISSUE TITLE
Installation not possible

### ISSUE THREAD

**Issue by pxlcore** [InfotelGLPI/mydashboard#52]
After copying the files to the server and starting Install in GLPI admin panel this error shows up:

`1.0.4 multiple alter in glpi_plugin_mydashboard_userwidgets -error in database request: ALTER TABLE 'glpi_plugin_mydashboard_userwidgets' ADD 'interface' TINYINT(1) NOT NULL DEFAULT '0' - error is: Table 'helpdesk.glpi_plugin_mydashboard_userwidgets' doesn't exist `

Plugin: mydashboard 1.6.1
GLPI: 9.3.1 and 9.3.2

**Comment by keha35** [comment]
Hi,

Can you check if all glpi's table are in InnoDB?
If it's not the case, can you switch all tables to InnoDB and uninstall/reinstall the plugin ?

**Comment by pxlcore** [comment]
Hi,
all tables are in InnoDb.

I have a table glpi_plugin_mydashboard_**widgets** but not glpi_plugin_mydashboard_**userwidgets**. Might this be the reason?

**Comment by keha35** [comment]
I cant reproduce,
Have you tried to unistall and reinstall the plugin?
