### ISSUE TITLE
Problem with central interface

### ISSUE THREAD

**Issue by Juju34de7** [InfotelGLPI/mydashboard#54]
Version of GLPI: 9.3.3
Versions of plugin: 1.6.1/1.6.2/1.6.3

Hello all,

i am not a developer at all (I am a french systems administrator) and I am testing your plugin.
I have a problem with the configuration: the plugin always replaces the central interface, even when I change that in the plugin configuration. (I have tested with 3 versions of plugin, always the same problem).

Thanks a lot for your help, and thanks a lot for all your work, you are awesome.

**Comment by yalgva** [comment]
I confirm this behavior (glpi9.3.2 - mydashboard 1.6.1) the value is not modified in database even if you modify in GLPI

Thank you

**Comment by keha35** [comment]
There is two configuration for replacing the central interface : 
- One in the plugin configuration
- One in the préférences of the user

**Comment by Juju34de7** [comment]
Yes, you're right, I tested and all works fine, I close the issue, thank you!
