### ISSUE TITLE
Add widget

### ISSUE THREAD

**Issue by Gwenaelle93** [InfotelGLPI/mydashboard#55]
Hello 
would it be possible to add a widget to be able to display in the Dashboard the tasks on the changes and the tasks on the problems by assistant ? 

- The version of the plugin, mydashboard :  1.6.3
- The version of your GLPI : 9.3.3

thank you in advance

**Comment by keha35** [comment]
For plugin evolutions, it is necessary to go through a specific development that we realize for our customers.
