### ISSUE TITLE
glpi status alert is not set up correctly

### ISSUE THREAD

**Issue by yalgva** [InfotelGLPI/mydashboard#58]
Hello,

glpi 9.3.3 / mydashboard 1.6.4

IIS/php 7.2 curl activated

Glpi status ok directly on the web page, however on mydashboard widget I have this message

Thx for your help and your great job !
![image](https://user-images.githubusercontent.com/30655170/52326912-73005b00-29ea-11e9-8d6e-6a272f60ca9d.png)
![image](https://user-images.githubusercontent.com/30655170/52326923-7c89c300-29ea-11e9-966f-1918c8635b88.png)

**Comment by tsmr** [comment]
Have you SSO activated into IIS ?

**Comment by yalgva** [comment]
no

**Comment by mrcssilvasouza** [comment]
In version 1.7.1 for GLPI 9.4.1.1 also presents the same error.

**Comment by tsmr** [comment]
Old ticket i close
