### ISSUE TITLE
Only I can use the plugin?

### ISSUE THREAD

**Issue by LuminousWing** [InfotelGLPI/mydashboard#59]
I just installed the new version on gpli 9.4 and it's awesome.
Yet, it seems that only I can use the plugin and every other admin user can't access it. 

How can I make sure my other users can also use this plugin and not just me?

**Comment by keha35** [comment]
Hi,

Check the profiles rights in "Admininistration > Profiles > Dashboard access".

**Comment by LuminousWing** [comment]
That fixed it, thank you
