### ISSUE TITLE
Unable to let other group also use setup stock widgets

### ISSUE THREAD

**Issue by LuminousWing** [InfotelGLPI/mydashboard#60]
I have 2 admin groups,

1: Godmode
2: Super Admin

Godmode users can use the stock widgets to add to their dashboard, however in the mydashboard menu, I can't give the super admin group rights to use the stock widgets. When I activate it and click on save in the profile settings, it doesn't get saved.

Is this a bug or a function i'm unaware of?

**Comment by keha35** [comment]
Hi,

I think both users have personnals view.
To configure global view for a profil you need to use the edit mod and save the default view.

You can check if they have a personal view with the db (in glpi_plugin_mydashboard_dashboards)
If you have some rows with the users_id != 0 then it's that the user with this id has a personnal view.

**Comment by LuminousWing** [comment]
Hi,

I don't think this is the issue, the problem is that only I can choose from the "adda widget" menu in the mydashboard page.
Everyone else is unable to add any widgets, they get an empty list.
I want all the users in the super admin group to be able to configure their own dashboard with the widgets provided.

**Comment by tsmr** [comment]
and into glpi profiles ? profiles have rights to widgets ?

**Comment by LuminousWing** [comment]
No, that is what I meant, if I give them rights and save, it just gets unchecked again. It's quite annoying.

**Comment by mate-infotel** [comment]
Hi,
We released a new version of mydashboard (1.7.1). 
This version must solve your issue.

**Comment by keha35** [comment]
Without answer from you we close the issue.
Feel free to reopen it if needed.
