### ISSUE TITLE
mydashboard Widgets

### ISSUE THREAD

**Issue by mael-agro** [InfotelGLPI/mydashboard#68]
Bonjour,
J'ai télécharger le plugin mydashboard toutes fonction.
Mon problème et que quand je veux créer une alerte dans les widgets information j'ai pas les logos de types météo comme des nuages soleil. J'ai un logo Attention est quand je faits une supervision réseau j'ai un thermomètre. Est que vous savez comment mètre la météo ?

**Comment by mate-infotel** [comment]
Bonjour.

La widget Information n'est pas prévu pour afficher des informations spécifiques comme la météo.

Par contre les widgets personnalisées permettre d'afficher du code HTML/CSS/Javascript de votre choix.

Donc vous pouvez trouver du code qui affiche la météo et le mettre dans une widget personnalisée.

Bonne journée.

**Comment by mate-infotel** [comment]
Bonjour @mael-agro.

Tout d'abord merci de poser des questions en anglais pour que les anglophones puissent en profiter.

Cette fonctionnalité n'est pas prévue pour le moment sur le plugin mydashboard.

Dans les évolutions futures des widgets personnalisées permettront d'ajouter des informations de météo.

Pour le moment ce développement n'est pas prévu.

Nous réalisons des développements spécifiques pour nos clients. 
Vous pouvez nous contacter si vous en souhaitez.

Cordialement.
_______________________________________________________________________________________________________________

This fonctionnality is not planed for the moment for mydashboard plugin.

Futures évolutions of customs widgets will permit to add weather informations.

We do spécific developments for our customers. Contact us if you want.

Best regards.

**Comment by mate-infotel** [comment]
In next version of mydashboard we will enable javascript in custom widgets.
it will permit to add meteo widgets from websites like météo france.

So I close this issue.
