### ISSUE TITLE
My GLPI doesnt open after extracting mydashboard into plugins folders

### ISSUE THREAD

**Issue by Kurokat** [InfotelGLPI/mydashboard#7]
My GLPI doenst open when I extract mydashboard in the pugins folder.
GLPI Version 9.1

`[Tue Oct 25 21:22:59.441949 2016] [:error] [pid 1483] [client 89.248.172.90:46808] PHP Fatal error:  Uncaught Zend\\I18n\\Exception\\ParseException: Unknown or invalid$nvalid parser rule:  nplurals=INTEGER; plural=EXPRESSION; in /var/www/glpi/vendor/zendframework/zend-i18n/src/Translator/Plural/Rule.php:194\nStack trace:\n#0 /var/ww$var/www/glpi/vendor/zendframework/zend-i18n/src/Translator/Loader/Gettext.php(149): Zend\\I18n\\Translator\\Plural\\Rule::fromString(' nplurals=INTEG...')\n#1 /var/ww$var/www/glpi/vendor/zendframework/zend-i18n/src/Translator/Loader/Gettext.php(149): Zend\\I18n\\Translator\\Plural\\Rule::fromString(' nplurals=INTEG...')\n#1 /var/wwvar/www/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php(700): Zend\\I18n\\Translator\\Loader\\Gettext->load('en_GB', '/var/www/glpi/p...')\n#2 /var//var/www/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php(572): Zend\\I18n\\Translator\\Translator->loadMessagesFromFiles('mydashboard', 'en_GB')\n#B')\n#3 /var/www/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php(440): Zend\\I18n\\Translator\\Translator->loadMessages('mydashboard', 'en_GB')\n#4 )\n#4 /var/www/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php(354): Zend\\I18n\\Translator\\Translator->getTranslatedMessage('My Dashboard', 'en_GB'en_GB', 'mydashboard')\n#5 /va in /var/www/glpi/vendor/zendframework/zend-i18n/src/Translator/Plural/Rule.php on line 194`

**Comment by tsmr** [comment]
Which version of plugins have you download ?

**Comment by Kurokat** [comment]
Oh, I'm sorry, I forget to mention, it's version 1.3.0

**Comment by tsmr** [comment]
I cannot replicate... :(

**Comment by Kurokat** [comment]
How can I check this?
It's on the default folder, i haven't changed. My GLPI installation is new.

**Comment by tsmr** [comment]
You are in English on interface ?

**Comment by Kurokat** [comment]
Yes

**Comment by glpinewbi** [comment]
Same Problem here, i have upgraded to GLPI 9.1 (before 0.90.5) and extracted the "mydashboard 1.3.0 into plugin Folder after this my GLPI crashed and under Plugins (if GLPI is running) there are no plugins seen.

**Comment by Stoatwblr** [comment]
It's a plurality problem in the translation files. I will take a look and try to locate it.

**Comment by Stoatwblr** [comment]
The problem is the plural return in event.class.php line 37 - there's nothing defined in glpi.pot or the language files for it.

**Comment by tsmr** [comment]
I replicate :) - i will push a fix as soon as possible
(Change en_GB.po file - drop line "Plural-Forms: nplurals=INTEGER; plural=EXPRESSION;\n" & generate .mo)
Duplicate #9

**Comment by tsmr** [comment]
Can you try to download these files & replace into /plugins/mydashboard/locales & test ?

https://github.com/InfotelGLPI/mydashboard/blob/master/locales/en_GB.po
https://github.com/InfotelGLPI/mydashboard/raw/master/locales/en_GB.mo
