### ISSUE TITLE
Bug 1.7.3

### ISSUE THREAD

**Issue by yalgva** [InfotelGLPI/mydashboard#73]
Hello,

I tried to use your new plugin unfortunately, it does not work, I can use template but I can't add widget. if I try GLpi hang on

I have this message in debug

Fatal error: Uncaught Error: Call to a member function fetch_array() on bool in C:\inetpub\wwwroot\inc\dbmysql.class.php:297 Stack trace: #0 C:\inetpub\wwwroot\plugins\mydashboard\inc\infotel.class.php(2102): DBmysql->fetch_array(false) #1 C:\inetpub\wwwroot\plugins\mydashboard\inc\widget.class.php(215): PluginMydashboardInfotel->getWidgetContentForItem('PluginMydashboa...', Array) #2 C:\inetpub\wwwroot\plugins\mydashboard\inc\widget.class.php(162): PluginMydashboardWidget::loadWidget('PluginMydashboa...', 'PluginMydashboa...', 'Graphiques', 'bt-col-md-11', Array) #3 C:\inetpub\wwwroot\plugins\mydashboard\inc\menu.class.php(1163): PluginMydashboardWidget::getWidget('gs17', Array, Array) #4 C:\inetpub\wwwroot\plugins\mydashboard\front\menu.php(116): PluginMydashboardMenu->loadDashboard('4', 0) #5 {main} thrown in C:\inetpub\wwwroot\inc\dbmysql.class.php on line 297

**Comment by mate-infotel** [comment]
Hi.

I draft a new release 1.7.4.
This must resolve your error.

It works ?

**Comment by yalgva** [comment]
I will check in 30 minutes 

Yannick Labbé

**Comment by yalgva** [comment]
Hello 
Solved in 1.7.4 thx
