### ISSUE TITLE
Erreur 1.0.4 multiple alter in glpi_plugin_mydashboard user widgets

### ISSUE THREAD

**Issue by mandream56** [InfotelGLPI/mydashboard#74]
Bonjour,

je viens d'installer la dernière version de GLPI la version 9.4.2 sur une Debian 9 avec 
Maridb 10.1 et base de donnée migrer d'une version 5.5 de MySQL (et d'une version antérieur de GLPI).

Je souhaite installer votre plugin, mais problème j'ai cette erreur quand je souhaite faire l'installation:
"1.0.4 multiple alter in glpi_plugin_mydashboard user widgets - Erreur durant l'exécution de la requête : ALTER TABLE `glpi_plugin_mydashboard_userwidgets` ADD `interface` TINYINT(1) NOT NULL DEFAULT '0' - L'erreur est Table 'glpi.glpi_plugin_mydashboard_userwidgets' doesn't exist"

Pour le test, j'ai installer un GLPI sur un serveur Debian 9 et MariaDB, pas d'import d'une base MySQL. Installation de votre plugin OK.

Seulement voila, je souhaite utilisé mon ancienne base de donnée, avec historique, parc, utilisateur, ....
Mais j'ai une erreur à l'installation de ce plugin.
J'ai désinstaller le plugin, refait le test en l'installant, vérifier les droits sur le dossier, bref je sèche.

Merci de votre aide.

Cordialement.

**Comment by keha35** [comment]
Bonjour,

Je pense qu'il s'agit d'un problème d'engine.
Pouvez vous vérifier si vos tables de Mydashboard sont bien en InnoDB?

**Comment by mandream56** [comment]
En vérifiant les tables dans ma base voila celle qui sont présente pour Mydashboard:

glpi.glpi_plugin_mydashboard_alerts                
glpi.glpi_plugin_mydashboard_profileauthorizedwidgets 
glpi.glpi_plugin_mydashboard_profiles              
glpi.glpi_plugin_mydashboard_widgets               

une partie de ma base est en MyISAM pour certains élément de GLPI comme par exemple glpi_wifinetworks, ....

**Comment by mandream56** [comment]
Ok je viens de faire une convertion du moteur de ma base MariaDB

Je viens de passer de MyISAM en Innodb, je viens de faire le test en installant le plugin et c'est OK.

Merci beaucoups.
