### ISSUE TITLE
number of opened and closed ticket by month (other issue)

### ISSUE THREAD

**Issue by yalgva** [InfotelGLPI/mydashboard#76]
Hello
glpi 9.4.2 - mydashboard 1.7.4

Since the last update the orange backlog is a bad value, it seems to be the same as total number of tickets.

![image](https://user-images.githubusercontent.com/30655170/59737917-b81d7f00-925f-11e9-9a9d-d33a2bd5e3da.png)

Thank you for your great job !

**Comment by tsmr** [comment]
Corrected for next version

https://github.com/InfotelGLPI/mydashboard/commit/4af0790298e7535055518b8546d2563e29aae69f
