### ISSUE TITLE
Can not display more than 10 items in ticket, tasks, etc. widgets

### ISSUE THREAD

**Issue by Synairgis** [InfotelGLPI/mydashboard#78]
Hi,

After to apply the differents patchs to you proposed to display item in widgets, I can't display more than 10 items in ticket, tasks, widgets in plugin Mydashbord. Also the previous / next button doesn't work
- The version of the plugin: 1.7.4 and 1.6.8
- The version of your GLPI: 9.3.x or 9.4.x

Can you help to solve this problem?

**Comment by keha35** [comment]
Hi,

Is your issue still in progress?
Can you add screenshot to explain the probleme?
