### ISSUE TITLE
Create new widgets or find other widgets on the internet

### ISSUE THREAD

**Issue by maryy47** [InfotelGLPI/mydashboard#80]
Hi ! 

My plugin version of My Dashboard is1.7.4. 
GLPI version is 9.4.2.

This dashboard seems to be great ! But I would like to create my widgets or find others. Questions : 
- How to create my own widgets ?
- How to find existing widgets which are not installed by default ? 

One example : I want to display the number of opened tickets (simple !). How can I do that ? 

Thanks !

**Comment by keha35** [comment]
Hi, 

For now you can't create your own widgets without update the code.
We will think of this possibility for next releases.

Br.

**Comment by maryy47** [comment]
hi !

Thanks for your answer. I would like To display the number of opened tickets and the number of tickets of the currently  month. does it exists ?

Thanks !


Envoyé de mon Galaxy S7 edge Orange


-------- Message d'origine --------
De : Kevin HAINRY <notifications@github.com>
Date : 19/08/2019 10:41 (GMT+01:00)
À : InfotelGLPI/mydashboard <mydashboard@noreply.github.com>
Cc : Marie-Ange MALROUX <ma.malroux@polaris-wt.com>, Author <author@noreply.github.com>
Objet : Re: [InfotelGLPI/mydashboard] Create new widgets or find other widgets on the internet (#80)


Hi,

For now you can't create your own widgets without update the code.
We will think of this possibility for next releases.

Br.

**Comment by keha35** [comment]
Hi,

You can look at the widget : "Tickets stock by month"
I think it's what you want.

Br.

**Comment by maryy47** [comment]
Hi Kevin !

I added « tickets stock » but it’s a graphic :

[cid:image001.png@01D55988.CD691D20]

I need this one but I also would like to display these numbers of tickets :

  *   Opened tickets,
  *   Tickets opened today,
  *   Number of tickets in the month

Like this :

[cid:image002.png@01D55989.5155B260]

When you display it on a big screen, it’s easily readable than this :

[cid:image003.jpg@01D55989.5155B260]

Do you think it’s possible ?

Thanks !

Marie-Ange

De : Kevin HAINRY <notifications@github.com>
Envoyé : mardi 20 août 2019 17:38
À : InfotelGLPI/mydashboard <mydashboard@noreply.github.com>
Cc : Marie-Ange MALROUX <ma.malroux@polaris-wt.com>; Author <author@noreply.github.com>
Objet : Re: [InfotelGLPI/mydashboard] Create new widgets or find other widgets on the internet (#80)


Hi,

You can look at the widget : "Tickets stock by month"
I think it's what you want.

Br.

**Comment by maryy47** [comment]
Hi again !

That was my first needs. I have an other dashboard to make with :

Waiting duration,
Close delay stat,
Take into account delay stat,
Action time.

Here comes my SQL query :
SELECT AVG(waiting_duration/60) Tps_total_Traitement_Mn, AVG(close_delay_stat/60), AVG(takeintoaccount_delay_stat/60) Tps_Att_Affectation_Mn, AVG(actiontime/60) AS Tasks_Mn
FROM glpi_tickets
WHERE date_creation BETWEEN '2019-06-01' AND '2019-06-30'
AND is_deleted=0
ORDER BY id DESC

I just want to have a simple dashboard with the results for a month (in hours, in my query, it’s in minutes). I would like having something like that too, but about time statistics :
[cid:image002.png@01D55A5E.79530FD0]

Here comes my ideas, which are my needs. 😊

Marie-Ange

De : Marie-Ange MALROUX
Envoyé : vendredi 23 août 2019 08:04
À : InfotelGLPI/mydashboard <reply@reply.github.com>
Objet : RE: [InfotelGLPI/mydashboard] Create new widgets or find other widgets on the internet (#80)

Hi Kevin !

I added « tickets stock » but it’s a graphic :

[cid:image004.png@01D55A5E.79530FD0]

I need this one but I also would like to display these numbers of tickets :

  *   Opened tickets,
  *   Tickets opened today,
  *   Number of tickets in the month

Like this :

[cid:image002.png@01D55A5E.79530FD0]

When you display it on a big screen, it’s easily readable than this :

[cid:image005.jpg@01D55A5E.79530FD0]

Do you think it’s possible ?

Thanks !

Marie-Ange

De : Kevin HAINRY <notifications@github.com<mailto:notifications@github.com>>
Envoyé : mardi 20 août 2019 17:38
À : InfotelGLPI/mydashboard <mydashboard@noreply.github.com<mailto:mydashboard@noreply.github.com>>
Cc : Marie-Ange MALROUX <ma.malroux@polaris-wt.com<mailto:ma.malroux@polaris-wt.com>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Objet : Re: [InfotelGLPI/mydashboard] Create new widgets or find other widgets on the internet (#80)


Hi,

You can look at the widget : "Tickets stock by month"
I think it's what you want.

Br.

**Comment by tsmr** [comment]
Old ticket. I close
