### ISSUE TITLE
Number of opened tickets = 0

### ISSUE THREAD

**Issue by maryy47** [InfotelGLPI/mydashboard#82]
Hi !

First : here comes informations about my configuration :
- The version of the plugin : 1.7.4
- The version of your GLPI : 9.4.2

We use the plugin "Number of opened and closed tickets by month". Since august, the value of the curve "Number of opened tickets" is 0. I don't understand why, however, we have opened and closed tickets...

Thanks !

**Comment by yalgva** [comment]
Hello
Same for me on June

**Comment by Gwenaelle93** [comment]
Hello
Same for me since June

**Comment by keha35** [comment]
Hi, 

You need to add the script "insert_stock_ticket.php" in your crontab.

Br.

**Comment by maryy47** [comment]
Thanks for your help !
