### ISSUE TITLE
Plugin "MyDashboard" crashes the Plugin Folder

### ISSUE THREAD

**Issue by glpinewbi** [InfotelGLPI/mydashboard#9]
I have upgraded to GLPI 9.1 (before 0.90.5) and extracted the "mydashboard 1.3.0 into plugin Folder after this my GLPI crashed and under Plugins (if GLPI is running) there are no plugins seen Pls Fix this issue.

**Comment by Stoatwblr** [comment]
Ditto. The plugin folder is blank when mydashboard 1.3.0 is installed.

No errors logged.

**Comment by tsmr** [comment]
I replicate :) - i will push a fix as soon as possible
(Change en_GB.po file - drop line "Plural-Forms: nplurals=INTEGER; plural=EXPRESSION;\n" & generate .mo)

**Comment by tsmr** [comment]
Can you try to download these files & replace into /plugins/mydashboard/locales & test ?

https://github.com/InfotelGLPI/mydashboard/blob/master/locales/en_GB.po
https://github.com/InfotelGLPI/mydashboard/raw/master/locales/en_GB.mo

**Comment by glpinewbi** [comment]
Hey, i downloaded now the Updated Version from (http://plugins.glpi-project.org/#/plugin/mydashboard) but it still breaks my whole System. After putting the "mydashboard"- Folder into Plugin-Folder, i get "internal Server error.

**Comment by Stoatwblr** [comment]
Agreed. The bug's still there even with the latest commit.

The line you intended to drop is still there in the 1.3.1 release and https://github.com/InfotelGLPI/mydashboard/blob/master/locales/en_GB.po

Removing it and regenerating the mo file clears the fault.
