### ISSUE TITLE
Error with Glpi 9.4.5

### ISSUE THREAD

**Issue by buggzbeny** [InfotelGLPI/mydashboard#93]
Hello,

I try to upgrade my GLPI to 9.4.5. When i put this plugin version 1.7.7, all my plugin list is blank page.

![image](https://user-images.githubusercontent.com/45596518/77402976-caf54f00-6daf-11ea-8a46-c5530e6d686f.png)

 I can find them by typing name in search list and the plugin that i search appear above.

![image](https://user-images.githubusercontent.com/45596518/77403074-f37d4900-6daf-11ea-8f77-7027a50214e3.png)

But when i try to find mydashboard nothing. It is not listed 

![image](https://user-images.githubusercontent.com/45596518/77403150-1576cb80-6db0-11ea-930e-b08496b0e259.png)

When i remove mydashboard folder from glpi\plugins all my plugins are listed

![image](https://user-images.githubusercontent.com/45596518/77403279-5078ff00-6db0-11ea-90dd-4e5bb648b0dd.png)

Thanks.

**Comment by buggzbeny** [comment]
With version 1.7.6 it works ?!?

![image](https://user-images.githubusercontent.com/45596518/77404202-ab5f2600-6db1-11ea-9ade-33524cbdab71.png)

**Comment by tsmr** [comment]
Activate Debug Mode ?
