### ISSUE TITLE
Changes won't display on dashboard 

### ISSUE THREAD

**Issue by ajasa19** [InfotelGLPI/mydashboard#94]
- plugin: 1.7.7
- GLPI: 9.4.5

When I add a new change in Assistance/Change database and assign the change to a tech it's not showing up when I log into a user assigned as a technician. Both problems and tickets work fine. 
![Screenshot-2020-4-17 GLPI - Changes - 7](https://user-images.githubusercontent.com/61054231/79585722-345e3a00-809e-11ea-8bd5-1114f8ec9aa6.png)
![Screenshot-2020-4-17 GLPI - My Dashboard](https://user-images.githubusercontent.com/61054231/79585726-34f6d080-809e-11ea-9770-aeca43871c82.png)

**Comment by tsmr** [comment]
You change have New Status

It must be have $tab = [self::ACCEPTED, self::QUALIFICATION, self::TEST]; which are process statuses
