### ISSUE TITLE
Index labels always shown

### ISSUE THREAD

**Issue by sebliot** [InfotelGLPI/mydashboard#96]
Dear all,

 First I want to thank you for this new release of this powerfull plugin.
I wish this issue is not already exists because i looked for something similar in closed topics.
Version plugin: 1.7.7
Glpi Version : 9.4.5
![issueMydashboard](https://user-images.githubusercontent.com/56149673/81666678-a0845180-9442-11ea-961e-4eae77cbdd9b.JPG)

In a few words, in a widget you have added the features to unload a component in a graph with clic on it but the index labels are always shown.
I tried with another browser but I had same behavior.

I have no doubt this a known issue and hope you can correct it.
Thanks you Glpi Teams/ Merci à tous et vous avez fait un sacré travail moi qui l'utilise depuis des lustres.

Sebliot

**Comment by tsmr** [comment]
Hello

This is already fixed in the next version 👍
